login: &login
  username: bernardogalindo
  password: 

development:
  adapter: postgresql
  host: localhost
  database: caffetos_development 
  <<: *login
  
test:
  adapter: postgresql
  host: localhost
  database: caffetos_test  
  <<: *login   
  
production:
  adapter: postgresql
  host: localhost
  database: caffetos_production  
  <<: *login